# Basic workflow
name: build

# Controls when the action will run
# Workflow begins with push or PR events
# Focuses on the master branch only
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Create one signle job
# This job performs all necessary checks
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Performs all actions on different versions of Python
        python-version: [3.6, 3.7, 3.8]
    # Define workflow steps
    steps:
      # Checkout the code of the repository
      - name: Check out repository code
        uses: actions/checkout@v2
      # Run the mdl linting tool
      # Refers to .mdlrc file in repository
      - name: Run markdown linting
        uses: actionshub/markdownlint@master
      # Setup Python for the current language version
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build pyenv
        uses: gabrielfalcao/pyenv-action@v5
        with:
          default: "${{ matrix.python }}"
          command: pip install -U pip  # upgrade pip after installing python
      # Install pipenv
      - name: Install Pipenv
        run: |
          pip install pipenv
      # Install dependencies
      - name: Install dependencies
        run: |
          pipenv install --dev